language: php
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update --1
  - composer update $COMPOSER_FLAGS

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - bin/wsdl2php convert tests/config.yml tests/Fixtures/test.wsdl -vv

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

