language: php
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_script:
  - composer self-update --1
  - if [[ $TRAVIS_PHP_VERSION == '7.'* ]]; then composer --dev require ocramius/package-versions:^1.0 --no-update; fi
  - composer update $COMPOSER_FLAGS

script:
  - vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS
  - bin/wsdl2php convert tests/config.yml tests/Fixtures/test.wsdl -vv

